### ISSUE TITLE
training with multiple GPU with problem that the code is stuck

### ISSUE THREAD

**Issue by bowieshi** [NVlabs/ProtoMotions#30]
Hi. I can successfully train the code on a single GPU. After I modified the fabric.yaml file to the following, and train with command as following, my code is stuck and cannot continue to the data collection and training part. 
I am using 4 A100 to parralel the training process.  I run with 2048 num_env and batch_size of 8192. I also set the force_flat_terrain to be true

Also I want to inquire how many days you used to train a good full-body tracking policy on AMASS and samp. 

part of fabric.yaml
```
ngpu: 4
nodes: 1
torch_deterministic: False
amp_precision: 32-true
force_flat_terrain: False

eval_overrides:
  ngpu: 4
  nodes: 1

  fabric:
    loggers: null
```

training command
```
CUDA_VISIBLE_DEVICES=1,2,5,7 python phys_anim/train_agent.py \
    +exp=full_body_tracker \
    +robot=smplx \
    +backbone=isaacgym \
    motion_file=/media/xuzhao/Partition5/qyzheng/boao/AMASS-test/motion_file.pt \
    force_flat_terrain=True \
    algo.config.batch_size=8192 \
    num_envs=2048
```
The program is stuck here for a long time. So I need to kill it.
<img width="1148" alt="image" src="https://github.com/user-attachments/assets/eca86b2e-602e-41a7-946b-e2491151d402">
