### ISSUE TITLE
How to use scene_lib for interaction tasks training?

### ISSUE THREAD

**Issue by mulplue** [NVlabs/ProtoMotions#49]
Hi! I'd like to use the scene lib to train some interaction tasks, but I couldn't find any example scripts for using scene lib in the readme. I tried using:
```
python phys_anim/train_agent.py headless=False \
+exp=amp experiment_name=amp_smpl_walk_gym_test \
+robot=smpl motion_file=data/motions/smpl_humanoid_walk.npy \
+scenes=samp scene_file='data/yaml_files/samp_scenes_test.yaml' \
+backbone=isaacgym
```
but encountered a list overflow error. 
<img width="533" alt="image" src="https://github.com/user-attachments/assets/638b3755-0c82-4db7-8926-7dc3104f6863" />
I'm not sure if there's an issue with this script. Could you provide an example script for proper usage? Thanks very much! (Since the scene/object/robot spawn logic and offsets need to be consistent, I find it hard to add some objects without going through scene_lib)

**Comment by tesslerc** [comment]
Running the `full_body_tracker` experiment doesn't work?
That should spawn the SAMP scenes and provide an example for how the scene files are constructed.

Basically, a scene file is a list of scenes with unique ids.
Each scene is a list of objects.
Each object has a set of parameters, for example:
```
  - is_static: true  # is this fixed in place, or can the humanoid move it
    motion: data/assets/scenes/train/SAMP/Tables/836157300c030c9a246b9f2ca347e8e3.npy  # a file determining the object motion (examples are only for single pose = static objects)
    path: data/assets/scenes/train/SAMP/Tables/836157300c030c9a246b9f2ca347e8e3.urdf  # path to object
    object_options:  # parameters for convex decomposition
      vhacd_enabled: True
      vhacd_params:
        resolution: 50000
      fix_base_link: True  # identical to is_static. this is duplicated, should fix
      participates_in_heightmap: True  # whether the lidar projection (heightmap) observes this object. it's useful for large objects like sofa/chair. probably not very useful for small dynamic objects
```
