### ISSUE TITLE
Hydra config error in training

### ISSUE THREAD

**Issue by canoneod** [NVlabs/ProtoMotions#56]
Hello, I'm trying out newly pushed v2 over original repository, and have encountered an issue when I'm trying to train stage 1.

In config/env/base_env.yaml,

```
# @package _global_

defaults:
  - /terrain/flat
  - /motion_manager/base_manager

# Env structure
env:
  _target_: protomotions.envs.base_env.env.BaseEnv
  _recursive_: False
  config:
    experiment_name: ${experiment_name}
    num_envs: ${num_envs}
    headless: ${headless}
    
    simulator: ${simulator}
```
So I assumed keys in simulatr/base.yaml will show up on the run. But when instantiating env (`env = instantiate(config.env, device=fabric.device)`    in `train_agent.py`) when I check below part,

```
        SimulatorConfigClass = get_class(self.config.simulator._config_target_)
        simulator_config: SimulatorConfig = SimulatorConfigClass.from_dict(self.config.simulator.config)
        SimulatorClass = get_class(self.config.simulator._target_)    
```
There is no _config_target_ nor _target _ keys in `self.config.simulator`   (which is `self.config.env` in train_agent.py) and I'm getting error 

```
hydra.errors.InstantiationException: Error in call to target 'protomotions.envs.mimic.env.Mimic':
ConfigAttributeError('Missing key _config_target_\n    full_key: config.simulator._config_target_\n    object_type=dict')
full_key: env
```

When I print `config.env.config.simulator`, in train_agent.py it only has below parameters, neither `_config_target_` nor `_target_`

`{'sim': {'physx': {'num_position_iterations': 8, 'num_velocity_iterations': 1, 'default_buffer_size_multiplier': 10, 'contact_offset': 0.005, 'rest_offset': 0.0001}}}`

I added arguments correctly for training, and what could be the issue?

Also, I've recognized pretrained model of stage 2 disappeared on latest commit. Is it intended? 

Thanks in advance.
