### ISSUE TITLE
Training full body tracker on G1

### ISSUE THREAD

**Issue by Gabril17** [NVlabs/ProtoMotions#66]
Thanks for open sourcing your work. I am attempting to train a full body tracker on the Unitree G1 (23 DOF) robot using the V1 version of code, but encountering some problems.

The motion data is from AMASS dataset and have made the following modifications:
1. Modified the humanoid config in the **H1 retargeting process** to enable retargeting to the G1.
2. Added a **robot/g1.yaml**.

Here is the **g1.yaml** I added.

```
robot:
  dof_obs_size: ${eval:${len:${.isaacgym_dof_body_ids}}*6} 
  number_of_actions: 23
  self_obs_max_coords_size: 358

  isaacgym_dof_body_ids: [ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19,20,21,22,23 ]

  key_bodies: [ "left_ankle_roll_link", "right_ankle_roll_link" ]
  non_termination_contact_bodies: [ "left_ankle_roll_link", "right_ankle_roll_link" ]
  right_foot_name: "right_ankle_roll_link"
  left_foot_name: "left_ankle_roll_link"
  foot_name: "ankle_roll_link"
  knee_name: "knee_link"

  isaacgym_dof_names: [ 'left_hip_pitch_joint', 'left_hip_roll_joint', 'left_hip_yaw_joint', 'left_knee_joint', 'left_ankle_pitch_joint', 'left_ankle_roll_joint',
                        'right_hip_pitch_joint', 'right_hip_roll_joint', 'right_hip_yaw_joint', 'right_knee_joint', 'right_ankle_pitch_joint', 'right_ankle_roll_joint',
                        'waist_yaw_joint', 'waist_roll_joint', 'waist_pitch_joint',
                        'left_shoulder_pitch_joint', 'left_shoulder_roll_joint', 'left_shoulder_yaw_joint', 'left_elbow_joint',
                        'right_shoulder_pitch_joint', 'right_shoulder_roll_joint', 'right_shoulder_yaw_joint', 'right_elbow_joint' ]

  isaacgym_body_names: [ 'pelvis',
                         'left_hip_pitch_link', 'left_hip_roll_link', 'left_hip_yaw_link', 'left_knee_link', 'left_ankle_pitch_link', 'left_ankle_roll_link',
                         'right_hip_pitch_link', 'right_hip_roll_link', 'right_hip_yaw_link', 'right_knee_link', 'right_ankle_pitch_link', 'right_ankle_roll_link',
                         'waist_yaw_link', 'waist_roll_link', 'torso_link',
                         'left_shoulder_pitch_link', 'left_shoulder_roll_link', 'left_shoulder_yaw_link', 'left_elbow_link',
                         'right_shoulder_pitch_link', 'right_shoulder_roll_link', 'right_shoulder_yaw_link', 'right_elbow_link' ]

  init_state:
    pos: [ 0.0, 0.0, 0.8 ] 
    rot: [ 0.0, 0.0, 0.0, 1.0 ] 
    lin_vel: [ 0.0, 0.0, 0.0 ]
    ang_vel: [ 0.0, 0.0, 0.0 ]
    default_joint_angles:
      left_hip_pitch_joint: -0.1
      left_hip_roll_joint: 0.
      left_hip_yaw_joint: 0.
      left_knee_joint: 0.3
      left_ankle_pitch_joint: -0.2
      left_ankle_roll_joint: 0.
      right_hip_pitch_joint: -0.1
      right_hip_roll_joint: 0.
      right_hip_yaw_joint: 0.
      right_knee_joint: 0.3
      right_ankle_pitch_joint: -0.2
      right_ankle_roll_joint: 0.
      waist_yaw_joint: 0.
      waist_roll_joint: 0.
      waist_pitch_joint: 0.
      left_shoulder_pitch_joint: 0.
      left_shoulder_roll_joint: 0.
      left_shoulder_yaw_joint: 0.
      left_elbow_joint: 0.
      right_shoulder_pitch_joint: 0.
      right_shoulder_roll_joint: 0.
      right_shoulder_yaw_joint: 0.
      right_elbow_joint: 0.

  control:
    control_type: P
    stiffness:
      hip_yaw: 100    
      hip_roll: 100  
      hip_pitch: 100 
      knee: 200   
      ankle_pitch: 20   
      ankle_roll: 20   
      waist_yaw: 400   
      waist_roll: 400   
      waist_pitch: 400    
      shoulder_pitch: 90   
      shoulder_roll: 60   
      shoulder_yaw: 20   
      elbow: 60      
    damping: 
      hip_yaw: 2.5       
      hip_roll: 2.5     
      hip_pitch: 2.5       
      knee: 5       
      ankle_pitch: 0.2   
      ankle_roll: 0.1    
      waist_yaw: 5.0    
      waist_roll: 5.0     
      waist_pitch: 5.0  
      shoulder_pitch: 2.0  
      shoulder_roll: 1.0 
      shoulder_yaw: 0.4 
      elbow: 1.0    
    action_scale: 0.25
    clamp_actions: 100.0
  asset:
    collapse_fixed_joints: True
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.
    asset_file_name: "urdf/g1.urdf"
    robot_type: g1_29dof_anneal_23dof
    self_collisions: False 
    default_dof_drive_mode: 3
motion_lib:
  _target_: phys_anim.utils.motion_lib_g1.G1_MotionLib
env:
  config:
    simulator:
      sim:
        fps: 200 
        control_freq_inv: 4  
        substeps: 1

```
I am training the full body tracker on a single motion, using a training environment with 2x 4090 GPUs, a batch size of 2048, and 2048 environments. After training for over 8000 epochs, the result, as shown in the video, is that the robot immediately falls over at the start.

https://github.com/user-attachments/assets/647f6eef-399d-4195-9f0f-b40618f06273

The epoch length during training is shown in the attached image.

![Image](https://github.com/user-attachments/assets/2575661b-2e9b-427e-a7c1-c2f2dcd0aa32)

![Image](https://github.com/user-attachments/assets/29b0dfe8-16c6-4ef9-8028-ca88921d95e2)

Could you please help me solve this issue? I look forward to your reply!
